export const medicineGroups = [
    { "GroupName": "Generic Medicine", "NoOfMedicines": "02", "Action": "View Full Detail" },
    { "GroupName": "Diabetes", "NoOfMedicines": "32", "Action": "View Full Detail" },
    { "GroupName": "Cardiology", "NoOfMedicines": "15", "Action": "View Full Detail" },
    { "GroupName": "Neurology", "NoOfMedicines": "25", "Action": "View Full Detail" },
    { "GroupName": "Oncology", "NoOfMedicines": "08", "Action": "View Full Detail" },
    { "GroupName": "Dermatology", "NoOfMedicines": "18", "Action": "View Full Detail" },
    { "GroupName": "Gastroenterology", "NoOfMedicines": "12", "Action": "View Full Detail" },
    { "GroupName": "Pulmonology", "NoOfMedicines": "20", "Action": "View Full Detail" },
    { "GroupName": "Endocrinology", "NoOfMedicines": "10", "Action": "View Full Detail" },
    { "GroupName": "Hematology", "NoOfMedicines": "05", "Action": "View Full Detail" },
    { "GroupName": "Nephrology", "NoOfMedicines": "07", "Action": "View Full Detail" },
    { "GroupName": "Urology", "NoOfMedicines": "14", "Action": "View Full Detail" },
    { "GroupName": "Ophthalmology", "NoOfMedicines": "09", "Action": "View Full Detail" },
    { "GroupName": "Orthopedics", "NoOfMedicines": "06", "Action": "View Full Detail" },
    { "GroupName": "Pediatrics", "NoOfMedicines": "22", "Action": "View Full Detail" },
    { "GroupName": "Psychiatry", "NoOfMedicines": "13", "Action": "View Full Detail" },
    { "GroupName": "Rheumatology", "NoOfMedicines": "11", "Action": "View Full Detail" },
    { "GroupName": "Infectious Diseases", "NoOfMedicines": "17", "Action": "View Full Detail" },
    { "GroupName": "Geriatrics", "NoOfMedicines": "16", "Action": "View Full Detail" },
    { "GroupName": "Gynecology", "NoOfMedicines": "19", "Action": "View Full Detail" },
    { "GroupName": "General Surgery", "NoOfMedicines": "14", "Action": "View Full Detail" },
    { "GroupName": "Emergency Medicine", "NoOfMedicines": "21", "Action": "View Full Detail" },
    { "GroupName": "Anesthesiology", "NoOfMedicines": "08", "Action": "View Full Detail" },
    { "GroupName": "Allergy and Immunology", "NoOfMedicines": "12", "Action": "View Full Detail" },
    { "GroupName": "Rehabilitation Medicine", "NoOfMedicines": "07", "Action": "View Full Detail" },
    { "GroupName": "Pain Management", "NoOfMedicines": "09", "Action": "View Full Detail" },
    { "GroupName": "Sports Medicine", "NoOfMedicines": "06", "Action": "View Full Detail" },
    { "GroupName": "Transplant Medicine", "NoOfMedicines": "03", "Action": "View Full Detail" },
    { "GroupName": "Critical Care Medicine", "NoOfMedicines": "20", "Action": "View Full Detail" },
    { "GroupName": "Occupational Medicine", "NoOfMedicines": "11", "Action": "View Full Detail" },
    { "GroupName": "Family Medicine", "NoOfMedicines": "15", "Action": "View Full Detail" },
    { "GroupName": "Palliative Care", "NoOfMedicines": "04", "Action": "View Full Detail" },
    { "GroupName": "Neonatology", "NoOfMedicines": "18", "Action": "View Full Detail" },
    { "GroupName": "Hepatology", "NoOfMedicines": "05", "Action": "View Full Detail" },
    { "GroupName": "Vascular Medicine", "NoOfMedicines": "13", "Action": "View Full Detail" },
    { "GroupName": "Infectious Disease", "NoOfMedicines": "10", "Action": "View Full Detail" },
    { "GroupName": "Radiology", "NoOfMedicines": "09", "Action": "View Full Detail" },
    { "GroupName": "Pathology", "NoOfMedicines": "16", "Action": "View Full Detail" },
    { "GroupName": "Clinical Pharmacology", "NoOfMedicines": "07", "Action": "View Full Detail" },
    { "GroupName": "Medical Genetics", "NoOfMedicines": "03", "Action": "View Full Detail" },
    { "GroupName": "Plastic Surgery", "NoOfMedicines": "02", "Action": "View Full Detail" },
    { "GroupName": "Thoracic Surgery", "NoOfMedicines": "06", "Action": "View Full Detail" },
    { "GroupName": "Neurosurgery", "NoOfMedicines": "05", "Action": "View Full Detail" },
    { "GroupName": "Oral and Maxillofacial Surgery", "NoOfMedicines": "08", "Action": "View Full Detail" },
    { "GroupName": "Otolaryngology", "NoOfMedicines": "14", "Action": "View Full Detail" },
    { "GroupName": "Pediatric Surgery", "NoOfMedicines": "12", "Action": "View Full Detail" },
    { "GroupName": "Trauma Surgery", "NoOfMedicines": "17", "Action": "View Full Detail" },
    { "GroupName": "Colorectal Surgery", "NoOfMedicines": "04", "Action": "View Full Detail" },
    { "GroupName": "General Medicine", "NoOfMedicines": "21", "Action": "View Full Detail" },
    { "GroupName": "Geriatric Medicine", "NoOfMedicines": "10", "Action": "View Full Detail" },
    { "GroupName": "Clinical Oncology", "NoOfMedicines": "08", "Action": "View Full Detail" }
]
